import type { DeviceConfig } from '../types/device';

/** Apple device definitions */
export const appleDevices: DeviceConfig[] = [
  {
    id: 'iphone-se-3',
    name: 'iPhone SE (3rd)',
    brand: 'apple',
    os: 'ios',
    screenWidth: 375,
    screenHeight: 667,
    devicePixelRatio: 2,
    screenRadius: 0,
    hasNotch: false,
    hasDynamicIsland: false,
    hasPunchHole: false,
    punchHolePosition: null,
    statusBarHeight: 20,
    navigationBarHeight: 0,
    homeIndicatorHeight: 0,
    frameColor: '#1a1a1a',
    year: 2022,
  },
  {
    id: 'iphone-14',
    name: 'iPhone 14',
    brand: 'apple',
    os: 'ios',
    screenWidth: 390,
    screenHeight: 844,
    devicePixelRatio: 3,
    screenRadius: 47,
    hasNotch: true,
    hasDynamicIsland: false,
    hasPunchHole: false,
    punchHolePosition: null,
    statusBarHeight: 47,
    navigationBarHeight: 0,
    homeIndicatorHeight: 34,
    frameColor: '#1a1a1a',
    year: 2022,
  },
  {
    id: 'iphone-14-pro',
    name: 'iPhone 14 Pro',
    brand: 'apple',
    os: 'ios',
    screenWidth: 393,
    screenHeight: 852,
    devicePixelRatio: 3,
    screenRadius: 55,
    hasNotch: false,
    hasDynamicIsland: true,
    hasPunchHole: false,
    punchHolePosition: null,
    statusBarHeight: 54,
    navigationBarHeight: 0,
    homeIndicatorHeight: 34,
    frameColor: '#2c2c2e',
    year: 2022,
  },
  {
    id: 'iphone-15',
    name: 'iPhone 15',
    brand: 'apple',
    os: 'ios',
    screenWidth: 393,
    screenHeight: 852,
    devicePixelRatio: 3,
    screenRadius: 55,
    hasNotch: false,
    hasDynamicIsland: true,
    hasPunchHole: false,
    punchHolePosition: null,
    statusBarHeight: 54,
    navigationBarHeight: 0,
    homeIndicatorHeight: 34,
    frameColor: '#1a1a1a',
    year: 2023,
  },
  {
    id: 'iphone-15-pro-max',
    name: 'iPhone 15 Pro Max',
    brand: 'apple',
    os: 'ios',
    screenWidth: 430,
    screenHeight: 932,
    devicePixelRatio: 3,
    screenRadius: 55,
    hasNotch: false,
    hasDynamicIsland: true,
    hasPunchHole: false,
    punchHolePosition: null,
    statusBarHeight: 54,
    navigationBarHeight: 0,
    homeIndicatorHeight: 34,
    frameColor: '#3a3a3c',
    year: 2023,
  },
  {
    id: 'iphone-16-pro',
    name: 'iPhone 16 Pro',
    brand: 'apple',
    os: 'ios',
    screenWidth: 402,
    screenHeight: 874,
    devicePixelRatio: 3,
    screenRadius: 55,
    hasNotch: false,
    hasDynamicIsland: true,
    hasPunchHole: false,
    punchHolePosition: null,
    statusBarHeight: 54,
    navigationBarHeight: 0,
    homeIndicatorHeight: 34,
    frameColor: '#2c2c2e',
    year: 2024,
  },
  {
    id: 'iphone-16-pro-max',
    name: 'iPhone 16 Pro Max',
    brand: 'apple',
    os: 'ios',
    screenWidth: 440,
    screenHeight: 956,
    devicePixelRatio: 3,
    screenRadius: 55,
    hasNotch: false,
    hasDynamicIsland: true,
    hasPunchHole: false,
    punchHolePosition: null,
    statusBarHeight: 54,
    navigationBarHeight: 0,
    homeIndicatorHeight: 34,
    frameColor: '#3a3a3c',
    year: 2024,
  },
];
