import type { DeviceConfig } from '../types/device';

/** Samsung device definitions */
export const samsungDevices: DeviceConfig[] = [
  {
    id: 'galaxy-s23',
    name: 'Galaxy S23',
    brand: 'samsung',
    os: 'android',
    screenWidth: 360,
    screenHeight: 780,
    devicePixelRatio: 3,
    screenRadius: 28,
    hasNotch: false,
    hasDynamicIsland: false,
    hasPunchHole: true,
    punchHolePosition: 'center',
    statusBarHeight: 24,
    navigationBarHeight: 48,
    homeIndicatorHeight: 0,
    frameColor: '#1a1a1a',
    year: 2023,
  },
  {
    id: 'galaxy-s24-ultra',
    name: 'Galaxy S24 Ultra',
    brand: 'samsung',
    os: 'android',
    screenWidth: 384,
    screenHeight: 824,
    devicePixelRatio: 3,
    screenRadius: 28,
    hasNotch: false,
    hasDynamicIsland: false,
    hasPunchHole: true,
    punchHolePosition: 'center',
    statusBarHeight: 24,
    navigationBarHeight: 48,
    homeIndicatorHeight: 0,
    frameColor: '#2c2c2e',
    year: 2024,
  },
  {
    id: 'galaxy-a54',
    name: 'Galaxy A54',
    brand: 'samsung',
    os: 'android',
    screenWidth: 360,
    screenHeight: 800,
    devicePixelRatio: 2,
    screenRadius: 24,
    hasNotch: false,
    hasDynamicIsland: false,
    hasPunchHole: true,
    punchHolePosition: 'center',
    statusBarHeight: 24,
    navigationBarHeight: 48,
    homeIndicatorHeight: 0,
    frameColor: '#1a1a1a',
    year: 2023,
  },
  {
    id: 'galaxy-z-fold5-cover',
    name: 'Galaxy Z Fold 5 (Cover)',
    brand: 'samsung',
    os: 'android',
    screenWidth: 374,
    screenHeight: 832,
    devicePixelRatio: 3,
    screenRadius: 24,
    hasNotch: false,
    hasDynamicIsland: false,
    hasPunchHole: true,
    punchHolePosition: 'center',
    statusBarHeight: 24,
    navigationBarHeight: 48,
    homeIndicatorHeight: 0,
    frameColor: '#1a1a1a',
    year: 2023,
  },
  {
    id: 'galaxy-z-fold5-inner',
    name: 'Galaxy Z Fold 5 (Inner)',
    brand: 'samsung',
    os: 'android',
    screenWidth: 882,
    screenHeight: 1104,
    devicePixelRatio: 2,
    screenRadius: 16,
    hasNotch: false,
    hasDynamicIsland: false,
    hasPunchHole: true,
    punchHolePosition: 'center',
    statusBarHeight: 24,
    navigationBarHeight: 48,
    homeIndicatorHeight: 0,
    frameColor: '#1a1a1a',
    year: 2023,
  },
  {
    id: 'galaxy-z-flip5',
    name: 'Galaxy Z Flip 5',
    brand: 'samsung',
    os: 'android',
    screenWidth: 360,
    screenHeight: 748,
    devicePixelRatio: 3,
    screenRadius: 24,
    hasNotch: false,
    hasDynamicIsland: false,
    hasPunchHole: true,
    punchHolePosition: 'center',
    statusBarHeight: 24,
    navigationBarHeight: 48,
    homeIndicatorHeight: 0,
    frameColor: '#2c2c2e',
    year: 2023,
  },
];
